### ISSUE TITLE
python five_chengben.py 报错

### ISSUE THREAD

**Issue by alanoy** [nessessary/autoxd#3]
MacOS 系统

```sh
/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5079: FutureWarning: Attribute 'is_copy' is deprecated and will be removed in a future version.
  object.__getattribute__(self, name)
/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5080: FutureWarning: Attribute 'is_copy' is deprecated and will be removed in a future version.
  return object.__setattr__(self, name, value)
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/MultiSubProcess/MultiSubProcess_exec.py", line 79, in <module>
    main(args)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/MultiSubProcess/MultiSubProcess_exec.py", line 59, in main
    r = myexec(s)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/pinyin/myexec.py", line 6, in myexec
    r = exec(s, globals(), _locals)
  File "<string>", line 2, in <module>
  File "/Users/alan/Documents/Stocks/autoxd/autoxd/strategy/five_chengben.py", line 268, in Run
    datasource_fn=fnSample
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/backtest_policy.py", line 146, in test_strategy
    p.Run(d1, d2)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/backtest_runner.py", line 88, in Run
    self._Report(policy, start_day, end_day, close)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/backtest_runner.py", line 204, in _Report
    title=title)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/ui.py", line 463, in TradeResult_Boll
    ShowTradeResult2(pl, bars, signals, zhijin,changwei , 0, freq=30, title=title)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/ui.py", line 429, in ShowTradeResult2
    pl.show()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/pypublish/publish.py", line 246, in show
    self.save()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/autoxd-0.4.3-py3.7.egg/autoxd/pypublish/publish.py", line 207, in save
    pl.savefig(fname, dpi=70)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 729, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2091, in print_figure
    **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    self._update_title_position(renderer)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2556, in _update_title_position
    if title.get_window_extent(renderer).ymin < top:
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 210, in get_text_width_height_descent
    font = self._get_agg_font(prop)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 246, in _get_agg_font
    font = get_font(fname)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1341, in get_font
    return _get_font(filename, hinting_factor)
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Fonts/STIXGeneral.otf'
```

**Comment by alanoy** [comment]
字体问题，已解决
